language: node_js
node_js:
  - 11.10.0
script:
  - yarn lint
  - yarn build:prod
  - yarn test
cache:
  directories:
    - 'node_modules'
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
