language: node_js
node_js:
  - 11.10.0
script:
  - yarn lint
  - yarn build:prod
  - yarn test
  - node createEnv.js
cache:
  directories:
    - 'node_modules'
deploy:
  skip_cleanup: true
  provider: script
  script: node deploy.js
  on:
    branch: master
